# Generated by Django 5.2.11 on 2026-04-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("farms", "0002_alter_farm_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_farm",
            field=models.ForeignKey(
                blank=True,
                help_text="Enterprise worker accounts use this to log activity under a head farmer farm.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workers",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_hash",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("FARMER", "Farmer"),
                    ("FARM_WORKER", "Farm Worker"),
                    ("VETERINARIAN", "Veterinarian"),
                    ("ADMIN", "Admin"),
                ],
                default="FARMER",
                max_length=20,
            ),
        ),
    ]
