# Generated by Django 5.2.11 on 2026-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_assigned_farm_user_otp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accessible_modules',
            field=models.JSONField(blank=True, default=list, help_text='List of frontend modules this worker can access'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('FARM_WORKER', 'Farm Worker'), ('VETERINARIAN', 'Veterinarian'), ('AGGREGATOR', 'Aggregator / Buyer'), ('ADMIN', 'Admin')], default='FARMER', max_length=20),
        ),
    ]
