# Generated by Django 5.2.11 on 2026-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_accessible_modules_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alt_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='indemnity_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='indemnity_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='worker_specialty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
