# Generated by Django 5.2.11 on 2026-02-13 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(choices=[('Dairy', 'Dairy'), ('General', 'General'), ('Surgery', 'Surgery'), ('Nutrition', 'Nutrition'), ('All', 'All')], max_length=50)),
                ('years_experience', models.PositiveIntegerField()),
                ('county', models.CharField(max_length=100)),
                ('sub_counties_covered', models.JSONField(default=list)),
                ('consultation_fee_kes', models.IntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='vet_photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vet_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VetAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='vets.vetprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VetVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('visit_type', models.CharField(choices=[('Routine', 'Routine'), ('Emergency', 'Emergency'), ('Vaccination', 'Vaccination'), ('Consultation', 'Consultation')], max_length=20)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cost_kes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_visits', to='farms.farm')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='vets.vetprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VetFarmConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('DECLINED', 'Declined'), ('REMOVED', 'Removed')], default='PENDING', max_length=20)),
                ('request_message', models.TextField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vet_connections', to='farms.farm')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='vets.vetprofile')),
            ],
            options={
                'unique_together': {('vet', 'farm')},
            },
        ),
        migrations.CreateModel(
            name='VetReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_vet_reviews', to='farms.farm')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vets.vetprofile')),
            ],
            options={
                'unique_together': {('vet', 'farm')},
            },
        ),
    ]
