# Generated by Django 5.2.11 on 2026-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vets', '0002_sharednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetprofile',
            name='clinic_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='clinic_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='emergency_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='indemnity_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='indemnity_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='kvb_reg_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vetprofile',
            name='qualifications',
            field=models.CharField(blank=True, default='BVM', max_length=150),
        ),
    ]
