# Generated by Django 5.2.11 on 2026-02-13 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Feed', 'Feed'), ('Veterinary', 'Veterinary'), ('Labor', 'Labor'), ('Equipment', 'Equipment'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=50)),
                ('amount_kes', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='farms.farm')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('MilkSale', 'Milk Sale'), ('AnimalSale', 'Animal Sale'), ('Other', 'Other')], max_length=50)),
                ('amount_kes', models.IntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('buyer_phone', models.CharField(blank=True, max_length=15)),
                ('mpesa_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='farms.farm')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_kes', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.CharField(choices=[('Subscription', 'Subscription'), ('MilkSale', 'Milk Sale')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_transactions', to='farms.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium'), ('Enterprise', 'Enterprise')], default='Basic', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount_kes', models.IntegerField(default=0)),
                ('mpesa_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_checkout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='farms.farm')),
            ],
        ),
    ]
