# Generated by Django 5.2.11 on 2026-04-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_alter_farm_name"),
        ("finance", "0002_alter_mpesatransaction_mpesa_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="features_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="subscription",
            name="last_payment_mode",
            field=models.CharField(default="test", max_length=20),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_ends_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="plan",
            field=models.CharField(
                choices=[
                    ("Trial", "Free Trial"),
                    ("Basic", "Basic"),
                    ("Premium", "Premium"),
                    ("Enterprise", "Enterprise"),
                ],
                default="Trial",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        choices=[
                            ("Trial", "Free Trial"),
                            ("Basic", "Basic"),
                            ("Premium", "Premium"),
                            ("Enterprise", "Enterprise"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount_kes", models.IntegerField()),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TEST_APPROVED", "Test Approved"),
                            ("PENDING_KEYS", "Waiting for API Keys"),
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("provider", models.CharField(default="mpesa", max_length=30)),
                ("test_mode", models.BooleanField(default=True)),
                ("checkout_request_id", models.CharField(blank=True, max_length=100)),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to="farms.farm",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_intents",
                        to="finance.subscription",
                    ),
                ),
            ],
        ),
    ]
