# Generated by Django 5.2.11 on 2026-02-13 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ear_tag', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('breed', models.CharField(choices=[('Friesian', 'Friesian'), ('Ayrshire', 'Ayrshire'), ('Jersey', 'Jersey'), ('Guernsey', 'Guernsey'), ('Mixed', 'Mixed'), ('Other', 'Other')], default='Mixed', max_length=20)),
                ('sex', models.CharField(choices=[('Bull', 'Bull'), ('Heifer', 'Heifer'), ('Cow', 'Cow')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Pregnant', 'Pregnant'), ('Dry', 'Dry'), ('Deceased', 'Deceased')], default='Healthy', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='animal_photos/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='farms.farm')),
            ],
            options={
                'unique_together': {('farm', 'ear_tag')},
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('diagnosis', models.CharField(max_length=255)),
                ('treatment', models.TextField()),
                ('cost_kes', models.IntegerField()),
                ('next_checkup_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='animals.animal')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_health_records', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(limit_choices_to={'role': 'VETERINARIAN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100)),
                ('date_given', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('given_by', models.CharField(max_length=100)),
                ('batch_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.animal')),
            ],
        ),
    ]
