# Generated by Django 5.2.11 on 2026-10-09 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitypost_litres_available_and_more'),
        ('farms', '0004_farm_estimated_herd_size_farm_kdb_license_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymember',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_memberships', to='farms.farm'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_posts', to='farms.farm'),
        ),
    ]
