# Generated by Django 5.2.11 on 2026-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatorprofile',
            name='business_reg_no',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='indemnity_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='indemnity_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='kra_pin',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='office_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='aggregatorprofile',
            name='payment_terms',
            field=models.CharField(blank=True, default='Weekly', max_length=50),
        ),
    ]
