# Generated by Django 5.2.11 on 2026-10-08 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregators', '0002_aggregatorprofile_business_reg_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='alcohol_test_passed',
            field=models.BooleanField(default=True, help_text='Alcohol / clot-on-boiling rapid test'),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='lactometer_reading',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Specific gravity, e.g. 1.028', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='quality_grade',
            field=models.CharField(choices=[('GRADE_A', 'Grade A (Premium)'), ('GRADE_B', 'Grade B (Standard)'), ('REJECTED', 'Rejected')], default='GRADE_A', max_length=20),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='temperature_celsius',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Intake temperature in °C, e.g. 4.5', max_digits=4, null=True),
        ),
        migrations.CreateModel(
            name='AggregatorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='aggregators.aggregatorfarmconnection')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregator_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
