# Generated by Django 5.2.11 on 2026-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_workertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='estimated_herd_size',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='farm',
            name='kdb_license',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='primary_breed',
            field=models.CharField(blank=True, default='Friesian', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='size_acres',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
