# Generated by Django 5.2.11 on 2026-04-30 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("farms", "0002_alter_farm_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("AUTH", "Authentication"),
                    ("DATA_ENTRY", "Data Entry"),
                    ("SUBSCRIPTION", "Subscription"),
                    ("AI", "AI"),
                    ("COMMUNITY", "Community"),
                    ("SECURITY", "Security"),
                    ("API", "API"),
                ],
                default="API",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="farm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="farms.farm",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="method",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
